In [2]:
print("Hello!")  # shift + enter == evaluate+run the cell

Hello!


In [5]:
def hello(name):   # enter == go down one line
    return f'Hello, {name}!'  

for one_name in ['Tom', 'Dick', 'Harry', 'Reuven']:
    print(hello(one_name))  # shift + enter == run the cell

Hello, Tom!
Hello, Dick!
Hello, Harry!
Hello, Reuven!


In [7]:
# Jupyter command "c" copies the cell
# Jupyter command "v" pastes the cell
# Jupyter command "x" cuts the cell
# Jupyter command "z" -- undo!

# Jupyter command "l' -- help"
# Jupyter command "a" -- add cell above
# Jupyter command "b" -- add cell below

In [6]:
# green outline : typing into the cell
# blue outline: typing commands to Jupyter

In [6]:
# green outline : typing into the cell
# blue outline: typing commands to Jupyter

In [8]:
# Jupyter "magic" commands all start with %

# our most important magic command is:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [9]:
# warnings about Jupyter:

# (1) Jupyter command "r" turns your cell into text, not code!
#     Get back to coding with Jupyter command "y"

# (2) If you shift+enter multiple times in quick succession, you
#     will wedge Jupyter's Web interface.  You'll know this if
#    you see [*] on the left.  Use Kernel->Interrupt or
#     Kernel->Restart to make things work.


In [ ]:
# Exercise/practice/setup:

# (1) Install Jupyter (if you haven't already)
#     pip install jupyter (from the command line)
# (2) Run Jupyter from a terminal/cmd window
#    jupyter notebook
# (3) Start a new notebook
#    New-> Python 3 notebook
# (4) Write a simple "Hello, world" function (like mine, above)
#  that takes a name and returns a string with that name in it.
#  Run the function, as well.


In [10]:
# from the command line
# pip install -U numpy

In [11]:
# don't do this!
# import numpy   

In [12]:
# everyone does this!
import numpy as np

In [13]:
np

<module 'numpy' from '/usr/local/lib/python3.7/site-packages/numpy/__init__.py'>

In [14]:
# you don't even need to do that in Jupyter!  You can say
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [15]:
# NumPy n-dimensional array
# np.ndarray

In [16]:
# to create a NumPy array, just use np.array with a sequence
# string, list, tuple -- most often, we'll use a list

np.array([10, 20, 30, 40 ,50])

array([10, 20, 30, 40, 50])

In [17]:
np.array((10, 20, 30, 40 ,50))

array([10, 20, 30, 40, 50])

In [18]:
a = np.array([10, 20, 30, 40, 50])

In [19]:
a[0] # retrieve first item, index 0

10

In [20]:
a[3]  # retrieve item at index 3

40

In [21]:
a[1:4]  # slice from item 1 to (and not including) 4

array([20, 30, 40])

In [22]:
for one_item in a:
    print(one_item)

10
20
30
40
50


In [23]:
# Creating NumPy arrays:

np.array([10, 20, 30])

array([10, 20, 30])

In [24]:
np.array(range(10, 100, 10))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
# better: 
np.arange(10, 100, 10)   # better/faster than the previous one

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
np.arange(5)   # from 0 to 5 (not including)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(5,10)  # from 5 to 10

array([5, 6, 7, 8, 9])

In [28]:
np.zeros(10)   # returns an array of 10 zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.ones(10)  # returns an array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
# get 10 random integers from 0-100
np.random.randint(0, 100, 10)

array([ 7, 70, 14, 97, 84, 31, 66, 25, 96, 53])

In [31]:
# get 10 random floats from 0-1
np.random.rand(10)

array([0.15386151, 0.45416614, 0.1950965 , 0.76901417, 0.04726192,
       0.35009821, 0.36532143, 0.57948542, 0.63989203, 0.81505775])

In [32]:
# (1) Create a NumPy array with the integers from your birthdate (year,
#     month, and day)

# (2) Retrieve the year.

# (3) Replace the year with the current year.

# (4) Create a NumPy array containing every 3rd number from 567 to
#     890. What is the number at index 8 in this array?
#     What is the number at index 15?

In [33]:
a = np.array([1970, 7, 14])

In [34]:
a

array([1970,    7,   14])

In [35]:
type(a)

numpy.ndarray

In [36]:
a[0]

1970

In [37]:
a[0] = 2020
a

array([2020,    7,   14])

In [38]:
a

array([2020,    7,   14])

In [39]:
# (4) Create a NumPy array containing every 3rd number from 567 to
#     890. What is the number at index 8 in this array?
#     What is the number at index 15?

a = np.arange(567, 890, 3)
a

array([567, 570, 573, 576, 579, 582, 585, 588, 591, 594, 597, 600, 603,
       606, 609, 612, 615, 618, 621, 624, 627, 630, 633, 636, 639, 642,
       645, 648, 651, 654, 657, 660, 663, 666, 669, 672, 675, 678, 681,
       684, 687, 690, 693, 696, 699, 702, 705, 708, 711, 714, 717, 720,
       723, 726, 729, 732, 735, 738, 741, 744, 747, 750, 753, 756, 759,
       762, 765, 768, 771, 774, 777, 780, 783, 786, 789, 792, 795, 798,
       801, 804, 807, 810, 813, 816, 819, 822, 825, 828, 831, 834, 837,
       840, 843, 846, 849, 852, 855, 858, 861, 864, 867, 870, 873, 876,
       879, 882, 885, 888])

In [40]:
a[8]

591

In [41]:
a[15]

612

In [42]:
mylist = [10, 20, 30, 40, 50]
mylist + 5

TypeError: can only concatenate list (not "int") to list

In [43]:
mylist + mylist

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [44]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [45]:
a + a

array([ 20,  40,  60,  80, 100])

In [46]:
# NumPy arrays are *vectors* 
# it looks at index 0, and adds those together
# .. index 1
# .. index 2

In [49]:
a+a

array([ 20,  40,  60,  80, 100])

In [50]:
a-a

array([0, 0, 0, 0, 0])

In [51]:
a*a

array([ 100,  400,  900, 1600, 2500])

In [52]:
a/a

array([1., 1., 1., 1., 1.])

In [53]:
a+5   # broadcasting -- it applies the scalar to *EACH* element

array([15, 25, 35, 45, 55])

In [54]:
a-5

array([ 5, 15, 25, 35, 45])

In [55]:
a/5

array([ 2.,  4.,  6.,  8., 10.])

In [56]:
a*5

array([ 50, 100, 150, 200, 250])

In [57]:
a%5

array([0, 0, 0, 0, 0])

In [58]:
a**5

array([   100000,   3200000,  24300000, 102400000, 312500000])

In [59]:
a = np.array([10, 20, 30])
b = np.array([100, 200, 300, 400])

a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
# 10 ra
np.random.rand(10)