In [2]:
print("Hello!")  # shift + enter == evaluate+run the cell

Hello!


In [5]:
def hello(name):   # enter == go down one line
    return f'Hello, {name}!'  

for one_name in ['Tom', 'Dick', 'Harry', 'Reuven']:
    print(hello(one_name))  # shift + enter == run the cell

Hello, Tom!
Hello, Dick!
Hello, Harry!
Hello, Reuven!


In [7]:
# Jupyter command "c" copies the cell
# Jupyter command "v" pastes the cell
# Jupyter command "x" cuts the cell
# Jupyter command "z" -- undo!

# Jupyter command "l' -- help"
# Jupyter command "a" -- add cell above
# Jupyter command "b" -- add cell below

In [6]:
# green outline : typing into the cell
# blue outline: typing commands to Jupyter

In [6]:
# green outline : typing into the cell
# blue outline: typing commands to Jupyter

In [8]:
# Jupyter "magic" commands all start with %

# our most important magic command is:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [9]:
# warnings about Jupyter:

# (1) Jupyter command "r" turns your cell into text, not code!
#     Get back to coding with Jupyter command "y"

# (2) If you shift+enter multiple times in quick succession, you
#     will wedge Jupyter's Web interface.  You'll know this if
#    you see [*] on the left.  Use Kernel->Interrupt or
#     Kernel->Restart to make things work.


In [ ]:
# Exercise/practice/setup:

# (1) Install Jupyter (if you haven't already)
#     pip install jupyter (from the command line)
# (2) Run Jupyter from a terminal/cmd window
#    jupyter notebook
# (3) Start a new notebook
#    New-> Python 3 notebook
# (4) Write a simple "Hello, world" function (like mine, above)
#  that takes a name and returns a string with that name in it.
#  Run the function, as well.


In [10]:
# from the command line
# pip install -U numpy

In [11]:
# don't do this!
# import numpy   

In [12]:
# everyone does this!
import numpy as np

In [13]:
np

<module 'numpy' from '/usr/local/lib/python3.7/site-packages/numpy/__init__.py'>

In [14]:
# you don't even need to do that in Jupyter!  You can say
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [15]:
# NumPy n-dimensional array
# np.ndarray

In [16]:
# to create a NumPy array, just use np.array with a sequence
# string, list, tuple -- most often, we'll use a list

np.array([10, 20, 30, 40 ,50])

array([10, 20, 30, 40, 50])

In [17]:
np.array((10, 20, 30, 40 ,50))

array([10, 20, 30, 40, 50])

In [18]:
a = np.array([10, 20, 30, 40, 50])

In [19]:
a[0] # retrieve first item, index 0

10

In [20]:
a[3]  # retrieve item at index 3

40

In [21]:
a[1:4]  # slice from item 1 to (and not including) 4

array([20, 30, 40])

In [22]:
for one_item in a:
    print(one_item)

10
20
30
40
50


In [23]:
# Creating NumPy arrays:

np.array([10, 20, 30])

array([10, 20, 30])

In [24]:
np.array(range(10, 100, 10))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
# better: 
np.arange(10, 100, 10)   # better/faster than the previous one

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
np.arange(5)   # from 0 to 5 (not including)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(5,10)  # from 5 to 10

array([5, 6, 7, 8, 9])

In [28]:
np.zeros(10)   # returns an array of 10 zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.ones(10)  # returns an array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
# get 10 random integers from 0-100
np.random.randint(0, 100, 10)

array([ 7, 70, 14, 97, 84, 31, 66, 25, 96, 53])

In [31]:
# get 10 random floats from 0-1
np.random.rand(10)

array([0.15386151, 0.45416614, 0.1950965 , 0.76901417, 0.04726192,
       0.35009821, 0.36532143, 0.57948542, 0.63989203, 0.81505775])

In [32]:
# (1) Create a NumPy array with the integers from your birthdate (year,
#     month, and day)

# (2) Retrieve the year.

# (3) Replace the year with the current year.

# (4) Create a NumPy array containing every 3rd number from 567 to
#     890. What is the number at index 8 in this array?
#     What is the number at index 15?

In [33]:
a = np.array([1970, 7, 14])

In [34]:
a

array([1970,    7,   14])

In [35]:
type(a)

numpy.ndarray

In [36]:
a[0]

1970

In [37]:
a[0] = 2020
a

array([2020,    7,   14])

In [38]:
a

array([2020,    7,   14])

In [39]:
# (4) Create a NumPy array containing every 3rd number from 567 to
#     890. What is the number at index 8 in this array?
#     What is the number at index 15?

a = np.arange(567, 890, 3)
a

array([567, 570, 573, 576, 579, 582, 585, 588, 591, 594, 597, 600, 603,
       606, 609, 612, 615, 618, 621, 624, 627, 630, 633, 636, 639, 642,
       645, 648, 651, 654, 657, 660, 663, 666, 669, 672, 675, 678, 681,
       684, 687, 690, 693, 696, 699, 702, 705, 708, 711, 714, 717, 720,
       723, 726, 729, 732, 735, 738, 741, 744, 747, 750, 753, 756, 759,
       762, 765, 768, 771, 774, 777, 780, 783, 786, 789, 792, 795, 798,
       801, 804, 807, 810, 813, 816, 819, 822, 825, 828, 831, 834, 837,
       840, 843, 846, 849, 852, 855, 858, 861, 864, 867, 870, 873, 876,
       879, 882, 885, 888])

In [40]:
a[8]

591

In [41]:
a[15]

612

In [42]:
mylist = [10, 20, 30, 40, 50]
mylist + 5

TypeError: can only concatenate list (not "int") to list

In [43]:
mylist + mylist

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [44]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [45]:
a + a

array([ 20,  40,  60,  80, 100])

In [46]:
# NumPy arrays are *vectors* 
# it looks at index 0, and adds those together
# .. index 1
# .. index 2

In [49]:
a+a

array([ 20,  40,  60,  80, 100])

In [50]:
a-a

array([0, 0, 0, 0, 0])

In [51]:
a*a

array([ 100,  400,  900, 1600, 2500])

In [52]:
a/a

array([1., 1., 1., 1., 1.])

In [53]:
a+5   # broadcasting -- it applies the scalar to *EACH* element

array([15, 25, 35, 45, 55])

In [54]:
a-5

array([ 5, 15, 25, 35, 45])

In [55]:
a/5

array([ 2.,  4.,  6.,  8., 10.])

In [56]:
a*5

array([ 50, 100, 150, 200, 250])

In [57]:
a%5

array([0, 0, 0, 0, 0])

In [58]:
a**5

array([   100000,   3200000,  24300000, 102400000, 312500000])

In [59]:
a = np.array([10, 20, 30])
b = np.array([100, 200, 300, 400])

a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [60]:
# 10 random numbers (floats) from 0-1
np.random.rand(10)

array([0.193675  , 0.85918229, 0.2804377 , 0.05501046, 0.64461748,
       0.88693034, 0.4986411 , 0.77868014, 0.61637176, 0.37068003])

In [61]:
# 10 random numbers (floats) from 0-10
np.random.rand(10) * 10

array([0.40586788, 1.26299703, 1.00892395, 8.41946   , 8.98870768,
       5.00589523, 0.79675369, 6.33727612, 2.69282692, 5.75218072])

In [62]:
# start an array of 10 numbers, all equal to 6
np.ones(10) * 6

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [63]:
np.ones(5) + np.ones(5)

array([2., 2., 2., 2., 2.])

In [64]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [65]:
# methods that we can run on NumPy arrays!

In [67]:
# (1) help(np.array)

help(a)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [68]:
# (2) better way, I think, is to use "TAB" in Jupyter


In [69]:
a.sum()    # return the sum of a's elements

150

In [70]:
a.min()   # smallest value

10

In [71]:
a.max()  # largest value

50

In [72]:
a.mean()  # arithmetic mean -- same as a.sum()/len(a)

30.0

In [75]:
a.sum() / a.size

30.0

In [76]:
a.std()   # standard deviation 

14.142135623730951

In [78]:
# (1) Create an array of 10 random integers, from 0-100.

a = np.random.randint(0, 100, 10)
a

array([24, 32, 96, 23, 91, 47, 59, 43, 79, 17])

In [79]:
# (2) Find the mean and standard deviation of these numbers.  
a.mean()

51.1

In [80]:
a.std()

27.53706592939778

In [81]:
# (3) Create another array of 10 random integers, from 0-100.
b = np.random.randint(0, 100, 10)
b

array([81,  3, 12, 45, 48, 53, 82, 22, 40, 81])

In [82]:
# (4) Create a new, 2-element array whose elements are the average 
#   of those from each of the previous ones.  

c = np.array([a.mean(), b.mean()])
c

array([51.1, 46.7])

In [87]:
# (5) Create an array of 10 random floats, from 0-100.

a = np.random.rand(10) * 100
a

array([67.04179878, 60.7635865 , 27.83296977, 35.28247443, 15.14650217,
       26.08125533, 33.51790675, 49.78975774, 88.84722686, 92.31577749])

In [89]:
# (6) We would expect the mean to be approaximately 50.  Is it?  What's
#     the standard deviation?

a.mean()

49.661925581841814

In [90]:
a.std()

25.438997347489053

In [91]:
# (7) What are the min and max values?
a.min()

15.146502174541554

In [92]:
a.max()

92.31577748557362

In [93]:
a

array([67.04179878, 60.7635865 , 27.83296977, 35.28247443, 15.14650217,
       26.08125533, 33.51790675, 49.78975774, 88.84722686, 92.31577749])

In [94]:
a + 10

array([ 77.04179878,  70.7635865 ,  37.83296977,  45.28247443,
        25.14650217,  36.08125533,  43.51790675,  59.78975774,
        98.84722686, 102.31577749])

In [95]:
a

array([67.04179878, 60.7635865 , 27.83296977, 35.28247443, 15.14650217,
       26.08125533, 33.51790675, 49.78975774, 88.84722686, 92.31577749])

In [96]:
# index 3 from a
a[3]

35.28247442893105

In [97]:
# index 5 from a
a[5]

26.081255330766883

In [98]:
# both index 3 and 5 with "fancy indexing"
a[[3,5]]   # notice: list as an index

array([35.28247443, 26.08125533])

In [99]:
a[[3,5,3,5,4]]

array([35.28247443, 26.08125533, 35.28247443, 26.08125533, 15.14650217])

In [100]:
a + 10

array([ 77.04179878,  70.7635865 ,  37.83296977,  45.28247443,
        25.14650217,  36.08125533,  43.51790675,  59.78975774,
        98.84722686, 102.31577749])

In [101]:
a = np.random.randint(0, 50, 10)
a

array([39,  2, 47, 23, 16, 38, 19, 43, 42, 12])

In [102]:
a + 10

array([49, 12, 57, 33, 26, 48, 29, 53, 52, 22])

In [103]:
a + 33

array([72, 35, 80, 56, 49, 71, 52, 76, 75, 45])

In [108]:
a == 23  # compare 23 with each element in a
         # get an array of boolean values (True/False) back

array([False, False, False,  True, False, False, False, False, False,
       False])

In [109]:
a

array([39,  2, 47, 23, 16, 38, 19, 43, 42, 12])

In [110]:
a[3]

23

In [111]:
a[[3,5,7]]

array([23, 38, 43])

In [114]:
# use an array of booleans to retrieve from a
# where it's True, I get a value back
# where it's False, the value is ignored

# boolean index or a "mask" index
a[[True, False, True, False, True, False, True, False, True, False]]

array([39, 47, 16, 19, 42])

In [115]:
a[[True, False, True]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 3

In [116]:
# (a) we can apply equality operators via broadcast to a NumPy array
# (b) this returns a boolean array
# (c) we can apply a boolean array to retrieve selected items

In [117]:
a

array([39,  2, 47, 23, 16, 38, 19, 43, 42, 12])

In [118]:
a == 23

array([False, False, False,  True, False, False, False, False, False,
       False])

In [119]:
a[a==23]  # we're applying the boolean array as an index on a

array([23])

In [120]:
a[a>23]   # get all elements of a that are > 23

array([39, 47, 38, 43, 42])

In [121]:
a[a<50]

array([39,  2, 47, 23, 16, 38, 19, 43, 42, 12])

In [122]:
a[a<0]

array([], dtype=int64)

In [124]:
# (1) Create an array of 20 floats from 0-1,000.
# (2) Find the items that are less than the mean.
# (3) Find the items less than mean-std.

a = np.random.rand(20) * 1000
a

array([774.8342538 , 941.40286014, 757.88416195, 249.71050872,
       432.70040556, 347.72039362, 541.24727385, 968.38569401,
       165.37235099, 816.27822313, 396.89562493, 201.55839353,
       815.79638481, 951.49137743, 479.22713672, 406.34871424,
       472.72651737, 665.07432328, 432.54962107, 414.01119178])

In [127]:
a[a < a.mean()]

array([249.71050872, 432.70040556, 347.72039362, 541.24727385,
       165.37235099, 396.89562493, 201.55839353, 479.22713672,
       406.34871424, 472.72651737, 432.54962107, 414.01119178])

In [128]:
a.mean() - a.std()

312.8695920745376

In [131]:
# elements of a that are less than mean- 1 std
a[a < a.mean() - a.std()]

array([249.71050872, 165.37235099, 201.55839353])

In [132]:
a[a > a.mean() + a.std()]

array([941.40286014, 968.38569401, 816.27822313, 815.79638481,
       951.49137743])

In [133]:
a = np.random.randint(0, 100, 20)
a

array([25, 38,  9, 58, 29, 22, 84, 16, 69, 31, 42, 37, 71,  7, 88, 87, 61,
       63, 45, 61])

In [134]:
50 % 2  # % returns the remainder

0

In [135]:
51 % 2 

1

In [136]:
a % 2

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [137]:
a[a%2]  # I want all of the odd numbers... where a%2 is 1

array([38, 25, 38, 25, 38, 25, 25, 25, 38, 38, 25, 38, 38, 38, 25, 38, 38,
       38, 38, 38])

In [138]:
a

array([25, 38,  9, 58, 29, 22, 84, 16, 69, 31, 42, 37, 71,  7, 88, 87, 61,
       63, 45, 61])

In [140]:
# if we use an array of ints as an index, we get back
# fancy indexing -- the items at those indexes
a[a%2]   # don't do this!

array([38, 25, 38, 25, 38, 25, 25, 25, 38, 38, 25, 38, 38, 38, 25, 38, 38,
       38, 38, 38])

In [141]:
# if we use an array of booleans as an index, we get
# back those items that match True values

a[a%2 == 1]   # odd numbers in a

array([25,  9, 29, 69, 31, 37, 71,  7, 87, 61, 63, 45, 61])

In [142]:
a[a%2 == 0]   # even numbers in a

array([38, 58, 22, 84, 16, 42, 88])

In [143]:
# (1) Create an array of 20 random integers from 0 to 100.
a = np.random.randint(0, 100, 20)
a

array([14, 42, 18, 32, 47, 32, 77, 87, 56, 11, 38, 42, 94, 67, 77, 46,  0,
       10, 13, 57])

In [147]:
# (2) Find the largest even number.

a[a%2 == 0].max()

94

In [151]:
# (3) Find the mean of the odd numbers.
a[a%2 == 1].mean()

54.5

In [152]:
# Find even numbers greater than the mean
a

array([14, 42, 18, 32, 47, 32, 77, 87, 56, 11, 38, 42, 94, 67, 77, 46,  0,
       10, 13, 57])

In [153]:
a[a%2==0]

array([14, 42, 18, 32, 32, 56, 38, 42, 94, 46,  0, 10])

In [154]:
a[a>a.mean()]

array([47, 77, 87, 56, 94, 67, 77, 46, 57])

In [155]:
a[a%2==0 and a>a.mean()]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [156]:
s = 'abcd'
if s:
    print("The string is True-ish")
else:
    print("The string is False-ish")

The string is True-ish


In [157]:
s == True

False

In [158]:
s = ''
if s:
    print("The string is True-ish")
else:
    print("The string is False-ish")

The string is False-ish


In [160]:
a = np.array([])
if a:
    print("The array is True-ish")
else:
    print("The array is False-ish")

The array is False-ish


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  


In [162]:
a = np.array([0])
if a:
    print("The array is True-ish")
else:
    print("The array is False-ish")

The array is False-ish


In [168]:
# for "and" on arrays, use &
# for "or" on arrays, use |
# for "not" on arrays, use ~ (tilde)

a = np.array([14, 42, 18, 32, 47, 32, 77, 87, 56, 11, 38, 42, 94, 67, 77, 46,  0,
       10, 13, 57])

# to combine two conditions:
# (1) Use & or |
# (2) Use parentheses around each individual condition
a[(a%2==0) & (a>a.mean())]

array([56, 94, 46])

In [169]:
# (1) Create a NumPy array of 20 random integers from 0-100.
a = np.random.randint(0, 100, 20)
a

array([35, 86, 66, 55, 92, 64, 93, 59, 47, 38, 16, 53, 72, 84, 65, 11, 11,
       96, 57, 17])

In [174]:
# (2) What's the smallest even number greater than the mean?

a[(a%2==0) & (a>a.mean())].min()

64

In [177]:
# (3) Show all numbers either <mean-std or >mean+std.
a[(a<a.mean()-a.std())  |  (a>a.mean()+a.std())]

array([86, 92, 93, 16, 84, 11, 11, 96, 17])

In [179]:
# (4) Show odd numbers < mean and even numbers > mean.

a[(a%2==1) & (a<a.mean()) | 
  (a%2==0) & (a>a.mean())]

array([35, 86, 66, 55, 92, 64, 47, 53, 72, 84, 11, 11, 96, 17])

In [180]:
a

array([35, 86, 66, 55, 92, 64, 93, 59, 47, 38, 16, 53, 72, 84, 65, 11, 11,
       96, 57, 17])

In [181]:
a[5] = 9999
a

array([  35,   86,   66,   55,   92, 9999,   93,   59,   47,   38,   16,
         53,   72,   84,   65,   11,   11,   96,   57,   17])

In [182]:
# fancy indexing for assignment, not just retrieval
a[[3,7,11]] = 8888
a

array([  35,   86,   66, 8888,   92, 9999,   93, 8888,   47,   38,   16,
       8888,   72,   84,   65,   11,   11,   96,   57,   17])

In [183]:
# assign 12345 to all elements currently even
a[a%2==0] = 12345

In [184]:
a

array([   35, 12345, 12345, 12345, 12345,  9999,    93, 12345,    47,
       12345, 12345, 12345, 12345, 12345,    65,    11,    11, 12345,
          57,    17])

In [185]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [186]:
a[2] = 999
a

array([ 10,  20, 999,  40,  50])

In [187]:
a[2] = 123.456

In [188]:
a

array([ 10,  20, 123,  40,  50])

In [189]:
# arrays have two properties:
# (1) all elements have the same type
# (2) the length is fixed at creation time

In [190]:
a[3] = '1357'
a

array([  10,   20,  123, 1357,   50])

In [191]:
a[4] = 'abcd'

ValueError: invalid literal for int() with base 10: 'abcd'

In [192]:
a = np.array([10, 20, 30, 40, 50])


In [193]:
# type of an array is the "dtype"
a.dtype

dtype('int64')

In [ ]:
# four ways to indicate 64-bit ints:
np.dtype('int64')
dtype('int64')     # possible if you've used %pylab inline
np.int64
int64              # possible if you've used %pylab inline

In [194]:
a = np.array([10, 20, 30, 40, 50], dtype=np.int8)
a

array([10, 20, 30, 40, 50], dtype=int8)

In [195]:
# 1 billion rows of data, each is 64-bit int... 8 GB of data
# 1 billion rows of data, each is an 8-bit int... 1 GB of data

In [196]:
a

array([10, 20, 30, 40, 50], dtype=int8)

In [197]:
a * 10

array([ 100,  -56,   44, -112,  -12], dtype=int8)

In [198]:
a = np.array([10, 20, 30.5, 40, 50])
a

array([10. , 20. , 30.5, 40. , 50. ])

In [199]:
a.dtype

dtype('float64')

In [200]:
a = np.array([10, 20, 30, 40, 50])
a[2] = 123.456
a

array([ 10,  20, 123,  40,  50])

In [201]:
# NEVER EVER EVER assign to the dtype!
a.dtype = np.float64


In [202]:
a

array([4.94e-323, 9.88e-323, 6.08e-322, 1.98e-322, 2.47e-322])

In [203]:
a.dtype = np.int64
a

array([ 10,  20, 123,  40,  50])

In [204]:
# to turn an array into a new dtype, use "astype"
# this method returns a new array, based on the old one,
# with the new type

a

array([ 10,  20, 123,  40,  50])

In [205]:
a.astype(np.float64)

array([ 10.,  20., 123.,  40.,  50.])

In [206]:
a

array([ 10,  20, 123,  40,  50])

In [207]:
a = a.astype(np.float64)
a

array([ 10.,  20., 123.,  40.,  50.])

In [208]:
a = np.array('this is a test'.split())

In [209]:
a

array(['this', 'is', 'a', 'test'], dtype='<U4')

In [210]:
a[0]

'this'

In [211]:
a[1]

'is'

In [212]:
a[0] = 'abcdefghijkl'

In [213]:
a

array(['abcd', 'is', 'a', 'test'], dtype='<U4')

In [235]:
# (1) Create a NumPy array of 40 random integers, from 0-100.
a = np.random.randint(0, 100, 40)
a

array([33, 62, 55, 19, 22, 54,  8, 82, 29,  1, 52, 19, 73, 46, 44, 85, 56,
       48, 43, 10,  7, 15, 73, 46,  9, 70, 42, 19, 70, 12, 50, 65, 27, 70,
       43, 10, 96, 54, 88, 51])

In [236]:
a.mean()

43.95

In [237]:
a.std()

25.393847680097636

In [240]:
# (2) Find all numbers that are within 1 standard deviation of the mean,
#     and set them to be equal to the mean.  Has the mean changed?  Has
#     the std changed?

a = a.astype(np.float64)
a[(a>a.mean()-a.std()) & (a<a.mean()+a.std())] = a.mean()
a

array([43.15375, 62.     , 55.     , 19.     , 22.     , 54.     ,
       43.15375, 43.15375, 29.     , 43.15375, 43.15375, 19.     ,
       43.15375, 43.15375, 43.15375, 43.15375, 56.     , 43.15375,
       43.15375, 43.15375, 43.15375, 43.15375, 43.15375, 43.15375,
       43.15375, 43.15375, 43.15375, 19.     , 43.15375, 43.15375,
       43.15375, 65.     , 27.     , 43.15375, 43.15375, 43.15375,
       43.15375, 54.     , 43.15375, 43.15375])

In [241]:
a.mean()

42.232625

In [242]:
a.std()

9.997633867727153

In [243]:
# (2) Find all numbers that are within 1 standard deviation of the mean,
#     and set them to be equal to the mean.  Has the mean changed?  Has
#     the std changed?

a = a.astype(np.float64)
a[(a<a.mean()-a.std()) | (a>a.mean()+a.std())] = a.mean()
a

array([43.15375 , 42.232625, 42.232625, 42.232625, 42.232625, 42.232625,
       43.15375 , 43.15375 , 42.232625, 43.15375 , 43.15375 , 42.232625,
       43.15375 , 43.15375 , 43.15375 , 43.15375 , 42.232625, 43.15375 ,
       43.15375 , 43.15375 , 43.15375 , 43.15375 , 43.15375 , 43.15375 ,
       43.15375 , 43.15375 , 43.15375 , 42.232625, 43.15375 , 43.15375 ,
       43.15375 , 42.232625, 42.232625, 43.15375 , 43.15375 , 43.15375 ,
       43.15375 , 42.232625, 43.15375 , 43.15375 ])

In [244]:
a.mean()

42.877412500000005

In [245]:
a.std()

0.42211250370162146

In [248]:
# (3) Create another NumPy array of 10 random integers, from 0-100.
a = np.random.randint(0, 100, 10)
a

array([46, 83, 97, 94, 37, 91, 68, 57, 36, 52])

In [247]:
# (4) Set the item at the even indexes to be equal to the items 
#     at the odd indexes.  So index 0 will get the value at 
#     index 1, etc.

a[[0,2,4,6,8]] = a[[1,3,5,7,9]]
a

array([10, 10, 18, 18, 84, 84, 48, 48, 40, 40])

In [250]:
np.arange(0, a.size, 2)

array([0, 2, 4, 6, 8])

In [251]:
a[np.arange(0, a.size, 2)] = a[np.arange(0, a.size, 2) + 1]

In [252]:
a

array([83, 83, 94, 94, 91, 91, 57, 57, 52, 52])

In [254]:
scores = np.array([95, 97, 92, 96, 0])
scores.mean()

76.0

In [255]:
np.nan  # "not a number"

nan

In [256]:
# with %pylab inline in place, we can say "nan"
nan

nan

In [257]:
type(nan)

float

In [258]:
a = np.array([10, 20, nan, 40, 50])
a

array([10., 20., nan, 40., 50.])

In [259]:
a.dtype

dtype('float64')

In [260]:
a.mean() 

nan

In [261]:
# remove nan from the array

a[a!=nan]

array([10., 20., nan, 40., 50.])

In [262]:
nan == nan

False

In [263]:
nan != nan

True

In [264]:
# use np.isnan to find elements that are nan
np.isnan(a)

array([False, False,  True, False, False])

In [265]:
a[np.isnan(a)]

array([nan])

In [266]:
# use ~ (tilde) as a "not" with np.isnan and other NumPy operators
a[~np.isnan(a)]

array([10., 20., 40., 50.])

In [267]:
a[~np.isnan(a)].mean()

30.0

In [268]:
scores = np.array([95, 97, 92, 96, nan])
scores.mean()

nan

In [270]:
# what was the mean, ignoring nan values?
scores[~np.isnan(scores)].mean()

95.0

In [271]:
# interpolation
# method 2: find nan values, and assign them something else
scores

array([95., 97., 92., 96., nan])

In [272]:
# calculate the mean of the non-nan values
# assign the mean of non-nan values to all nans
# result: mean is unchanged, and we can calculate it
scores[np.isnan(scores)] = scores[~np.isnan(scores)].mean()

In [273]:
scores.mean()

95.0

In [274]:
scores

array([95., 97., 92., 96., 95.])

In [275]:
# (1) Create a NumPy array of 20 random floats from 0-100.
a = np.random.rand(20) * 100
a

array([17.79090048, 34.79171401, 99.33187226, 52.84668164, 27.7326224 ,
       26.39727484, 46.58202797, 44.02653676, 61.28743652, 19.53144755,
       77.82889496, 76.94538967, 87.18971282, 18.11736485, 19.14844243,
       56.64919132, 89.17218532, 86.04375464, 61.14101087, 23.47493426])

In [281]:
# (2) Replace those numbers whose int portion is even with the mean.
#     (So 20.5 would be replaced, but 21.5 would not be.)

a[a.astype(np.int64) % 2 == 0] = a.mean()
a

array([17.79090048, 51.30146978, 99.33187226, 51.30146978, 27.7326224 ,
       51.30146978, 51.30146978, 51.30146978, 61.28743652, 19.53144755,
       77.82889496, 51.30146978, 87.18971282, 51.30146978, 19.14844243,
       51.30146978, 89.17218532, 51.30146978, 61.14101087, 23.47493426])

In [282]:
# (3) Create a NumPy array of 30 random ints from 0-1000.
a = np.random.randint(0, 1000, 30)
a

array([ 70, 812, 943, 101, 193, 662, 585, 581, 900, 295, 492, 815, 299,
       540, 670, 202,  54, 484, 225,  67, 509, 939, 209, 772, 749, 900,
       822, 282, 226, 925])

In [286]:
# (4) Find the numbers that are <mean-std or >mean+std, 
#     and set them to be nan (remember: nan is a float!)

a = a.astype(np.float64)
a[(a<a.mean()-a.std()) | (a>a.mean()+a.std())] = nan

In [287]:
a

array([ nan,  nan,  nan,  nan,  nan, 662., 585., 581.,  nan, 295., 492.,
        nan, 299., 540., 670.,  nan,  nan, 484., 225.,  nan, 509.,  nan,
        nan, 772., 749.,  nan,  nan, 282., 226.,  nan])

In [292]:
# (5) Now change those nan values to be the mean of the array's
#     elements.

a[np.isnan(a)] = a[~np.isnan(a)].mean()
a

array([491.4, 491.4, 491.4, 491.4, 491.4, 662. , 585. , 581. , 491.4,
       295. , 492. , 491.4, 299. , 540. , 670. , 491.4, 491.4, 484. ,
       225. , 491.4, 509. , 491.4, 491.4, 772. , 749. , 491.4, 491.4,
       282. , 226. , 491.4])

In [293]:
type(a)

numpy.ndarray

In [294]:
# ndarray == n-dimensional array

In [295]:
a = np.array([[10, 20, 30, 40],
             [50, 60, 70, 80],
             [90, 100, 110, 120]])
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [296]:
a.shape  # returns a tuple showing the length in each dimension

(3, 4)

In [297]:
a[1]

array([50, 60, 70, 80])

In [298]:
a[2]

array([ 90, 100, 110, 120])

In [299]:
a = np.random.randint(0, 100, 24)
a

array([33, 18, 60, 54, 83,  3, 89, 68, 19, 34,  9, 54, 22, 75, 66, 96, 11,
       91, 51, 12, 93, 32, 28, 82])

In [300]:
a.shape = (4,6)


In [301]:
a

array([[33, 18, 60, 54, 83,  3],
       [89, 68, 19, 34,  9, 54],
       [22, 75, 66, 96, 11, 91],
       [51, 12, 93, 32, 28, 82]])

In [302]:
a.reshape(8,3)

array([[33, 18, 60],
       [54, 83,  3],
       [89, 68, 19],
       [34,  9, 54],
       [22, 75, 66],
       [96, 11, 91],
       [51, 12, 93],
       [32, 28, 82]])

In [303]:
a

array([[33, 18, 60, 54, 83,  3],
       [89, 68, 19, 34,  9, 54],
       [22, 75, 66, 96, 11, 91],
       [51, 12, 93, 32, 28, 82]])

In [304]:
a = np.random.randint(0, 100, [4,6])
a

array([[38, 20, 13, 91,  1, 80],
       [97, 95,  9, 11, 31, 83],
       [18, 29, 41, 78, 76, 53],
       [19, 44, 82, 31,  3, 98]])

In [305]:
a[1]

array([97, 95,  9, 11, 31, 83])

In [306]:
# fancy indexing -- retrieving multiple rows
a[[1,3]]

array([[97, 95,  9, 11, 31, 83],
       [19, 44, 82, 31,  3, 98]])

In [307]:
a

array([[38, 20, 13, 91,  1, 80],
       [97, 95,  9, 11, 31, 83],
       [18, 29, 41, 78, 76, 53],
       [19, 44, 82, 31,  3, 98]])

In [309]:
a[2][2]  # don't do this!

41

In [310]:
a[2,2] # this is the NumPy way!

41

In [311]:
# get one column
a[:,2]   # all rows, column index 2

array([13,  9, 41, 82])

In [312]:
# fancy indexing  -- get more than one column
a[:, [2,4]]

array([[13,  1],
       [ 9, 31],
       [41, 76],
       [82,  3]])

In [313]:
a

array([[38, 20, 13, 91,  1, 80],
       [97, 95,  9, 11, 31, 83],
       [18, 29, 41, 78, 76, 53],
       [19, 44, 82, 31,  3, 98]])

In [314]:
a.sum()  

1141

In [315]:
# pass the axis to sum (and other aggregation methods)
# axis = 0 means: x axis, get a new row
a.sum(axis=0)

array([172, 188, 145, 211, 111, 314])

In [316]:
# axis=1 means: y axis, get a new column
a.sum(axis=1)

array([243, 326, 295, 277])

In [317]:
# (1) Create a 2-dimensional NumPy array of 45 random integers, 
# from 0-100.

a = np.random.randint(0, 100, [5,9])
a

array([[69, 44, 19, 48, 10, 81, 25, 10, 16],
       [66, 98, 54, 95,  6, 87, 27, 27, 64],
       [17, 50, 67, 29, 89, 74, 97,  8, 70],
       [75, 19, 93, 21, 52, 82, 96, 81, 69],
       [92, 32, 79, 68, 13, 62, 39, 38, 39]])

In [318]:
# (2) Retrieve the elements at row index 2.
a[2]

array([17, 50, 67, 29, 89, 74, 97,  8, 70])

In [319]:
# (3) Retrieve the elements at column index 3.
a[:, 3]

array([48, 95, 29, 21, 68])

In [321]:
# (4) Retrieve the elements at row indexes 1 and 4.
a[[1,4]]

array([[66, 98, 54, 95,  6, 87, 27, 27, 64],
       [92, 32, 79, 68, 13, 62, 39, 38, 39]])

In [322]:
# (5) Retrieve the elements at column indexes 1 and 4.
a[:, [1,4]]

array([[44, 10],
       [98,  6],
       [50, 89],
       [19, 52],
       [32, 13]])

In [326]:
# (6) Get the mean of the even numbers in row index 4.
a[4][a[4]%2 == 0].mean()

58.4

In [330]:
# (7) Get the mean of the odd numbers in column index 4.
a[:,4][a[:,4]%2==1].mean()

51.0