In [2]:
print("Hello!")  # shift + enter == evaluate+run the cell

Hello!


In [5]:
def hello(name):   # enter == go down one line
    return f'Hello, {name}!'  

for one_name in ['Tom', 'Dick', 'Harry', 'Reuven']:
    print(hello(one_name))  # shift + enter == run the cell

Hello, Tom!
Hello, Dick!
Hello, Harry!
Hello, Reuven!


In [7]:
# Jupyter command "c" copies the cell
# Jupyter command "v" pastes the cell
# Jupyter command "x" cuts the cell
# Jupyter command "z" -- undo!

# Jupyter command "l' -- help"
# Jupyter command "a" -- add cell above
# Jupyter command "b" -- add cell below

In [6]:
# green outline : typing into the cell
# blue outline: typing commands to Jupyter

In [6]:
# green outline : typing into the cell
# blue outline: typing commands to Jupyter

In [8]:
# Jupyter "magic" commands all start with %

# our most important magic command is:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [9]:
# warnings about Jupyter:

# (1) Jupyter command "r" turns your cell into text, not code!
#     Get back to coding with Jupyter command "y"

# (2) If you shift+enter multiple times in quick succession, you
#     will wedge Jupyter's Web interface.  You'll know this if
#    you see [*] on the left.  Use Kernel->Interrupt or
#     Kernel->Restart to make things work.


In [ ]:
# Exercise/practice/setup:

# (1) Install Jupyter (if you haven't already)
#     pip install jupyter (from the command line)
# (2) Run Jupyter from a terminal/cmd window
#    jupyter notebook
# (3) Start a new notebook
#    New-> Python 3 notebook
# (4) Write a simple "Hello, world" function (like mine, above)
#  that takes a name and returns a string with that name in it.
#  Run the function, as well.


In [10]:
# from the command line
# pip install -U numpy

In [11]:
# don't do this!
# import numpy   

In [12]:
# everyone does this!
import numpy as np

In [13]:
np

<module 'numpy' from '/usr/local/lib/python3.7/site-packages/numpy/__init__.py'>

In [14]:
# you don't even need to do that in Jupyter!  You can say
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [15]:
# NumPy n-dimensional array
# np.ndarray

In [16]:
# to create a NumPy array, just use np.array with a sequence
# string, list, tuple -- most often, we'll use a list

np.array([10, 20, 30, 40 ,50])

array([10, 20, 30, 40, 50])

In [17]:
np.array((10, 20, 30, 40 ,50))

array([10, 20, 30, 40, 50])

In [18]:
a = np.array([10, 20, 30, 40, 50])

In [19]:
a[0] # retrieve first item, index 0

10

In [20]:
a[3]  # retrieve item at index 3

40

In [21]:
a[1:4]  # slice from item 1 to (and not including) 4

array([20, 30, 40])

In [22]:
for one_item in a:
    print(one_item)

10
20
30
40
50


In [23]:
# Creating NumPy arrays:

np.array([10, 20, 30])

array([10, 20, 30])

In [24]:
np.array(range(10, 100, 10))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
# better: 
np.arange(10, 100, 10)   # better/faster than the previous one

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(5)   # from 0 to 5 (not including)